// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// disco_optimized_rcpp
arma::vec disco_optimized_rcpp(const arma::mat& d, const arma::mat& d2, const arma::mat& weight, int ncores);
RcppExport SEXP _DISCO4HD_disco_optimized_rcpp(SEXP dSEXP, SEXP d2SEXP, SEXP weightSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(disco_optimized_rcpp(d, d2, weight, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DISCO4HD_disco_optimized_rcpp", (DL_FUNC) &_DISCO4HD_disco_optimized_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DISCO4HD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
