# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disco_optimized_rcpp <- function(d, d2, weight, ncores = 4L) {
    .Call(`_DISCO4HD_disco_optimized_rcpp`, d, d2, weight, ncores)
}

